author: DomanoSV
description: MaintenanceMode bukkit plugin.
name: MaintenanceMode
version: 0.3.0
main: net.dkebnh.bukkit.MaintenanceMode.MaintenanceMode
load: STARTUP
url: http://www.dkebnh.net/
commands:
    mm:
        description: MaintenanceModes standard command variable.
        usage: /mm help for more information.
        aliases: [mm]
    mmedit:
        description: MaintenanceModes standard command variable.
        usage: /mmedit help for more information.
        aliases: [mmedit]
    mmstatus:
        description: MaintenanceModes standard command variable.
        usage: /mmstatus help for more information.
        aliases: [mmstatus]