name: MaintenanceMode
version: ${pom.version}
description: MaintenanceMode bukkit plugin.
main: net.dkebnh.bukkit.MaintenanceMode.MaintenanceMode
load: STARTUP
softdepend: [PlaceholderAPI]
commands:
    mm:
        description: MaintenanceModes standard command variable.
        usage: /mm help for more information.
        aliases: [mm]
    mmedit:
        description: MaintenanceModes standard command variable.
        usage: /mmedit help for more information.
        aliases: [mmedit]
    mmstatus:
        description: MaintenanceModes standard command variable.
        usage: /mmstatus help for more information.
        aliases: [mmstatus]